version: 2
updates:
  - package-ecosystem: "pip"
    assignees:
      - swimmwatch
    directory: "/"
    target-branch: develop
    schedule:
      interval: "daily"
    labels:
      - "pip"
      - "dependencies"

  - package-ecosystem: "npm"
    assignees:
      - swimmwatch
    directory: "/services/web/react-app"
    target-branch: develop
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "npm"
    assignees:
      - swimmwatch
    directory: "/services/overwolf_app"
    target-branch: develop
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "github-actions"
    assignees:
      - swimmwatch
    directory: "/"
    target-branch: develop
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"